### ISSUE TITLE
Volt directory can't be written

### ISSUE THREAD

**Issue by naaness** [phalcon/box#55]
Hi All, congratulations for your excellent work!!
I have the next problem, I try to make "chmod -R 777" on "/home/vagrant/workspace/phalcon/cache/" and it does not change, what do I do? Thanks!!

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by naaness** [comment]
Thanks man!!

**Comment by sergeyklay** [comment]
Fixed in the master branch
