### ISSUE TITLE
Create workspace folder

### ISSUE THREAD

**Issue by Jurigag** [phalcon/box#69]
If workspace folder doesn't exists, then create default one with old `index.php` and `.manager` from old vagrant box(1.2.0 tag).

**Comment by sergeyklay** [comment]
We released the 2.x version which is completely not backward compatible with 1.x. If you need the functionality of a 1.x version, please use the appropriate tag.

**Comment by sergeyklay** [comment]
And yes, Phalcon Box does not expect the `workspace` folder or any other. It is just example. You can use `C:\Jurigag` for Windows or `~/xxx` for Linux. Just point it in `settings.yml`

**Comment by Jurigag** [comment]
Oh okay then. It was just better if you previously wrote 192.168.50.4 and you had anything displayed, right now there is just File not found.

**Comment by sergeyklay** [comment]
Can you create an issue by using [our issue template](https://github.com/phalcon/box/issues/new)?

**Comment by Jurigag** [comment]
But this is exactly why this is this problem, yea i can create but it will be similar - create some default workspace if there is none, best with just simple index.php and .manager from old vagrant box.

**Comment by sergeyklay** [comment]
> File not found.

I need full vagrant log, settings.yml, OS, versions, steps to reproduce and installed software - all that is described in issue template.
