### ISSUE TITLE
box can add  the swoole extension ?

### ISSUE THREAD

**Issue by kideny** [phalcon/box#76]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

## Steps to reproduce

> Provide minimal script/step to reproduce the issue

1.  pecl install swoole
2.  edit php.ini
3.  add extension=swoole.so

### Expected behavior

> Describe what you are trying to achieve and what goes wrong.

the box should add the swoole extension。

### Actual behavior

> What actually happened?

### Host operating system

> This is the operating system that you run locally.

### `settings.yml`

```yaml
# Copy-paste your settings.yml here
```

### Vagrant up output

> Provide output if related.
> Provide a link to a GitHub Gist containing the complete output.
> Do NOT paste the debug output in the issue, just paste the link to the Gist.

### Details

- Vagrant: Run `vagrant -v` to show the version
- Provider: Virtualbox, VMWare or Parallels and it's version
- Phalcon Box: Run `git describe --tags --abbrev=0` to show the version
- Operating System:
- Other related info (if any):

NOTE: A lot of issues can be resolved by simply updating Vagrant, VM provider or Phalcon Box.

Virtualbox users, please upgrade to `~5.1`. You will show as up-to-date from the `~5.0` branch when you
`About -> Check for Updates`. You'll need to download a newer version of Virtualbox. 
See: https://www.virtualbox.org/wiki/Downloads

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by kideny** [comment]
please visit the url ，http://pecl.php.net/package/swoole

**Comment by sergeyklay** [comment]
@kideny You can use `after_provision.sh` script to install all additional extensions
