### ISSUE TITLE
Add wkhtmltopdf to the VM, set the default nginx config to show indexes (file listing)

### ISSUE THREAD

**Issue by icaroscherma** [phalcon/box#77]
Hello, since the package of the dev-env is in a full stack, would be nice to add a Webkit PDF Generation tool like wkhtmltopdf.
Also the default nginx config file doesn't show directory listing (`autoindex`), would be nice to have it. =)

**Comment by sergeyklay** [comment]
Fixed in the 2.4.0 version. See [Custom Nginx configuration](https://github.com/phalcon/box#custom-nginx-configuration) and [Install aditional packages](https://github.com/phalcon/box#install-aditional-packages)
