### ISSUE TITLE
Phalcon Box needs Vagrant >= 1.9.8

### ISSUE THREAD

**Issue by davidsierradz** [phalcon/box#87]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

## Steps to reproduce

> Provide minimal script/step to reproduce the issue

1. Clone this repository
2. Run vagrant up

### Expected behavior

> Describe what you are trying to achieve and what goes wrong.

Run vagrant up successfully.

### Actual behavior

> What actually happened?

```bash
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/shell/provisioner.rb:268:in `gsub!': can't modify frozen String (RuntimeError)
```

### Host operating system

> This is the operating system that you run locally.

### `settings.yml`

Default `settings.yml``

### Vagrant up output

> Provide output if related.
> Provide a link to a GitHub Gist containing the complete output.
> Do NOT paste the debug output in the issue, just paste the link to the Gist.

### Details

I was able to ssh into the box with Vagrant 1.9.8, maybe put in the `Vagrantfile`

```ruby
Vagrant.require_version '>= 1.9.8'
```

**Comment by sergeyklay** [comment]
Fixed in latest stable release. Thank you
