### ISSUE TITLE
Unable to cd to workspace

### ISSUE THREAD

**Issue by maxi032** [phalcon/box#93]
I have vagrant 2.0.1 on windows 10 and virtualBox 5.1.30 with phalconphp/xenial64 (virtualbox, 2.1.1)
Everything works fine with provisioning: I get pbox: Phalcon Box provisioned!
but after I do vagrant ssh and cd workspace nothing happends

**Comment by sergeyklay** [comment]
Could you provide your settings.yml

**Comment by maxi032** [comment]
Turns out that cd works but the cursor is not the default one. It does not show the user and path at the prompt... it just stays idle and blinks: "|" :)

**Comment by maxi032** [comment]
<code>
---
# ------------------------------------------------------------
# Phalcon Box Configurations
# ------------------------------------------------------------
#

# Name of VM
name: pbox

# VM provider
#
# Available providers:
#   - virtualbox
#   - vmware_fusion
#   - vmware_workstation
provider: virtualbox

# Enable GUI mode (show screen of VM)
gui: false

ip: "192.168.50.4"

# memory (in MB):
#   auto -> 1/4 of system RAM
#   1536 -> 1.5 GB RAM
memory: 4096

# cpu:
#   auto -> max number of CPU cores
#      2 -> 2 CPU cores
cpus: 2

# vram (in MB):
#   video memory (currently vbox only)
vram: 100

# Provisioning features
provision:
    # do full system update for each full provisoning
    update: false

    # apt packages
    apt: []

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/workspace/phalcon
      to: /home/vagrant/workspace/phalcon
      
    - map: C:\Users\user\MyPhalconApps
      to: /home/vagrant/workspace
      
    - map: C:\Users\user\MyPhalconApps\pma
      to: /home/vagrant/workspace/pma  

# Sites configuration.
#
# You can use the "type" parameter to specify the type
# of Nginx configuration for the site. For example:
#
# - map:  landing.local
#   to:   /home/vagrant/workspace/landing/public
#   type: spa
#
# The default type is "phalcon".
#
# If the desired type is not allowed "phalcon" will be used as fallback.
#
# Available types:
#   - phalcon
#   - slayer
#   - phanbook
#   - proxy
#   - spa
#   - silverstripe
#   - symfony2
#   - statamic
#   - laravel
#   - zend
sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/phalcon/public

   - map: yona-cms.phloc
      to: /home/vagrant/workspace/yona-cms/public 
   
    - map: pma.phloc
      to: /home/vagrant/workspace/pma
    
    - map: laravel55.phloc
      to: /home/vagrant/workspace/laravel55/public
      type: laravel

   - map: slayer.phloc
      to: /home/vagrant/workspace/slayer/public
      type: slayer

        
    
databases:
    - phalcondb
    - laravel55
    - slayer

#blackfire:
#    - id: foo
#      token: bar
#      client_id: foo
#      client_token: bar

ports:
    - send: 9200
      to: 9200
#    - send: 50000
#      to: 5000
#    - send: 7777
#      to: 777
#      protocol: udp

# verbose:
#   Set provision verbosity to obtain detailed logging.
#   Default value is false (minimal verbosity). Examples:
#
#   false -> minimal verbosity
#    true -> equivalent to v
#    -vvv -> equivalent to vvv
#    vvvv -> maximal verbosity
verbose: false
</code>

**Comment by maxi032** [comment]
<code>
name: pbox

provider: virtualbox

gui: false

ip: "192.168.50.4"

memory: 4096

cpus: 2

vram: 100

provision:
    update: false

    apt: []

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/workspace/phalcon
      to: /home/vagrant/workspace/phalcon
      
    - map: C:\Users\user\MyPhalconApps
      to: /home/vagrant/workspace
      
    - map: C:\Users\user\MyPhalconApps\pma
      to: /home/vagrant/workspace/pma  

sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/phalcon/public
      
    - map: pma.phloc
      to: /home/vagrant/workspace/pma
    
    - map: laravel55.phloc
      to: /home/vagrant/workspace/laravel55/public
      type: laravel

    - map: slayer.phloc
      to: /home/vagrant/workspace/slayer/public
      type: slayer

    - map: yona-cms.phloc
      to: /home/vagrant/workspace/yona-cms/public  
      
    - map: testing.phloc
      to: /home/vagrant/workspace/testing  
        
      

databases:
    - phalcondb
    - laravel55
    - blogcraftable
    - slayer


ports:
    - send: 9200
      to: 9200

verbose: false
</code>

**Comment by sergeyklay** [comment]
Is `cd` to other paces (for example `cd /home` ) works as expected?

**Comment by maxi032** [comment]
Now vagrant up is not working

<pre>$ vagrant up
Bringing machine 'pbox' up with 'virtualbox' provider...
==> pbox: Checking if box 'phalconphp/xenial64' is up to date...
==> pbox: Clearing any previously set forwarded ports...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "0ee64ce7-f94d-4851-a71f-3a02a3d65092", "--natpf1", "delete", "127.0.0.1tcp27017", "--natpf1", "delete", "127.0.0.1tcp33060", "--natpf1", "delete", "127.0.0.1tcp44300", "--natpf1", "delete", "127.0.0.1tcp54320", "--natpf1", "delete", "127.0.0.1tcp8000", "--natpf1", "delete", "127.0.0.1tcp8025", "--natpf1", "delete", "127.0.0.1tcp9200", "--natpf1", "delete", "ssh"]

Stderr: VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 507 of file VBoxManageModifyVM.cpp
</pre>

I think this is an issue that has to do with the new vagrant version.

**Comment by sergeyklay** [comment]
I recommend updating to the latest VirtualBox and Vagrant, reinstalling Phalcon Box and trying `vagrant up` again.

**Comment by maxi032** [comment]
I upgraded all..,the problem still persists. It is a vagrant issue and here are more users with the same problem: https://github.com/hashicorp/vagrant/issues/9143
The solution is to use VAGRANT_PREFER_SYSTEM_BIN=1 before vagrant ssh
